
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 936496
	#The name of the modpack
	modpackName = "Arcane Sanctum-Adventure & fun"
	#The version of the modpack
	modpackVersion = "B-0.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

